# -*- coding: utf-8 -*-
"""20230913_4120E017.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHl4uKVmvN0g74sLEy_zMtx0EbgxEHji
"""

3**211